# mike nugent, jr
# data analyst, indygo
# jan 21, 2020

### --- Purpose --- ###

# this script will pull data from GFI reports and reverse engineer the RouteSum report

### --- Revision History --- ###

### --- Notes --- ###
# this script relies on the Monthly Summary Report, the RouteSum Report, and the Transaction List Report generated by GFI


### --- Libraries --- ###

library(tidyverse)
library(hablar)
library(data.table)

### --- Begin --- ###

### STEP 1 --> Read the rules into a data frame so we can match them later


# ms_first <- ms_filepath %>%
#   read_lines() %>%
#   grep("Ridership is defined",.)
# ms_last <- ms_filepath %>%
#   readLines() %>%
#   grep("excluded", .)-1
# ms_dirty_test <- ms_filepath %>%
#   read.table(skip = ms_first, header = FALSE, nrows = ms_last-ms_first, sep = ",")
  
# find fare structure table and read it into a dataframe


ms_filepath <- dir('data//raw//', full.names = T, pattern = "MONTHLY SUMMARY")

readLines()

ms_dirty <- ms_filepath %>%
  readLines(con = .)

ms_first <- ms_dirty %>% 
  grep("Ridership is defined", .)+1

ms_last <- ms_dirty %>%
  grep("excluded", .)-1

ms_raw_rules <- data.frame(ms_dirty[ms_first:ms_last]) #read rules into dataframe
colnames(ms_raw_rules) <- "rules" #rename the column, just to make it easier to read
 
ms_clean_ridership_rules <- ms_raw_rules %>%
  separate_rows(names(.), sep = ",") %>%
  filter(!rules == "\"\"") %>% # spread the columns into two columns so the code matches description
  mutate(ind = rep(c(1,2),length.out = n())) %>%
  group_by(ind) %>%
  mutate(id = row_number()) %>%
  spread(ind, rules) %>%
  select(-id) %>%
  rename(
    Code = 1,
    Description = 2
  ) %>% # next two lines remove "" characters if we need them
   mutate(Code = substr(Code, 2, nchar(Code)-1)) %>%
   mutate(Description = substr(Description, 2, nchar(Description)-1))

### Step 2 --> Read the RouteSum Ridership

rs_filepath <- dir('data//raw//', full.names = T, pattern = "EVENT SUMMARY")

rs_ridership_first <- rs_filepath %>%
  readLines() %>%
  grep("Ridership By Route", .) %>%
  first()

rs_ridership_last <- rs_filepath %>%
  readLines() %>%
  grep("TOTAL",.)-1

rs_ridership_last <- rs_ridership_last[1]

rs_dirty <- rs_filepath %>%
  read.table(skip=rs_ridership_first, header = TRUE, nrows = rs_ridership_last-rs_ridership_first, sep = ",")

rs_clean <- rs_dirty %>%
  select(-starts_with("X"), -Token.Count, -Ticket.Count, -Preset.Preset1)


### Step 3 --> Read the transaction report in
td_filepath <- dir('data//raw//', full.names = T, pattern = "TRANSACTION DETAIL")

td_first <- td_filepath[7] %>%
  readLines() %>%
  grep("Type",.) %>%
  first()-1

td_last <- td_filepath[7] %>%
  readLines() %>%
  grep("Number of Tran",.)-2 %>%
  last()

td_dirty <- td_filepath[7] %>%
  read.table(skip=td_first, header = TRUE, nrows = td_last-td_first, sep =",")

td_clean <- td_dirty %>%
  select(-Direction, -Fareset, -Stop, -Trip) %>%
  convert(chr(Type,
              Bus,
              Route,
              Run,
              Driver,
              Description))
  
### Sep 4 Sum by Accepted ID?
ridership_test <- td_clean %>%
  filter(Description %in% ms_clean_ridership_rules$Code) %>%
  group_by(Route) %>%
  summarize(count = n()) %>%
  arrange(as.integer(Route)) %>%
  rename(Ridership_mine = count)

fare_diff <- ridership_test %>%
  inner_join(rs_clean, by = "Route") %>%
  select(Route, Ridership, Ridership_mine) %>%
  mutate(Ridership_diff = Ridership_mine-Ridership) %>%
  arrange(desc(Ridership_diff))

# the numbers do not match. let's look more closely at route 87,
# let's find out how much we're off by on this route
fare_diff %>%
  filter(Route == "87")

# we're off by twenty, which is... close!

# first split out route 87

route_87 <- td_clean %>%
  filter(Route == "87") %>%
  left_join(ms_clean_ridership_rules, by = c("Description" = "Code")) #add the code detail in case we need it

# compare transfers to ridership_diff,. if it's zero we're good
route_87 %>%
  filter(Type %like% "118") %>%
  count() %>%
  as.numeric()+ as.numeric(filter(fare_diff, Route == "87"))[4]

# bingo! let's apply transfers to the whole data frame
ridership_test_add_transfers <- td_clean %>%
  filter(Description %in% ms_clean_ridership_rules$Code | 
           Type %like% "118") %>%
  group_by(Route) %>%
  summarize(count = n()) %>%
  arrange(as.integer(Route)) %>%
  rename(mine_xfer = count)

# then join it to fare_diff again!
fare_diff <- fare_diff %>%
  inner_join(ridership_test_add_transfers, by = "Route") %>%
  mutate(xfer_diff = mine_xfer - Ridership)

head(fare_diff)
# and then let's find which routes still have differences, as well as their counts, we'll pick a small one

nonzero_diffs <- fare_diff %>%
  filter(xfer_diff != 0) %>%
  select(Route,
         Ridership,
         xfer_diff)
nonzero_diffs
# let's list what we're not including, then count each one and compare it to the sum of the nonzerodiffs, essentially we can do ths buy just doing the opposite of our filter earlier

#test with counts, sum should be count of rows of td_clean
count_used <- td_clean %>%
  filter(Description %in% ms_clean_ridership_rules$Code | 
           Type %like% "118") %>%
  count() %>%
  as.integer()

count_unused <- td_clean %>%
  filter(Description %in% ms_clean_ridership_rules$Code |
           Type %like% "118") %>%
  anti_join(td_clean, .) %>%
  count() %>%
  as.integer()

count_used + count_unused == count(td_clean)

# brilliant lets toss them together

unused <- td_clean %>%
  filter(Description %in% ms_clean_ridership_rules$Code |
           Type %like% "118") %>%
  anti_join(td_clean, .)

nonzero_diffs

route_25_td <- td_clean %>%
  filter(Route == "25") %>%
  left_join(ms_clean_ridership_rules, by = c("Description" = "Code")) %>%
  rename(CodeDesc = Description.y)

route_25_unused <- route_25_td  %>%
  filter(Description %in% ms_clean_ridership_rules$Code | 
           Type %like% "118") %>%
  anti_join(route_25_td, .)

#now lets count and group by code to see if we can find where our discrepencacy is coming from

route_25_unused %>%
    group_by(Description) %>%
    summarise(n = n())

route_25_unused %>%
  group_by(Type) %>%
  summarise(n=n())

head(route_25_td)
