# mike nugent, jr
# data analyst, indygo
# jan 21, 2020

### --- Purpose --- ###

# this script will be used to validate the RouteSum report using historical data

### --- Notes --- ###
# this script relies on the Monthly Summary Report, the RouteSum Report, and the Transaction List Report generated by GFI


### --- Libraries --- ###

library(tidyverse)
library(hablar)
library(data.table)
library(stringr)


##### STEP 1 --> Read the rules into a data frame
ms_filepaths <- dir('data//raw//', full.names = T, pattern = "MONTHLY SUMMARY")

MS_RulesImport <- function(ms_filepath){

    ms_dirty <- ms_filepath %>%
    readLines()
  
  ms_first <- ms_dirty %>% 
    grep("Ridership is defined", .)+1
  
  ms_last <- ms_dirty %>%
    grep("excluded", .)-1
  
  ms_raw_rules <- data.frame(ms_dirty[ms_first:ms_last]) #read rules into dataframe
  colnames(ms_raw_rules) <- "rules" #rename the column, just to make it easier to read
  
  ms_clean_ridership_rules <- ms_raw_rules %>%
    separate_rows(names(.), sep = ",") %>%
    filter(!rules == "\"\"") %>% # spread the columns into two columns so the code matches description
    mutate(ind = rep(c(1,2),length.out = n())) %>%
    group_by(ind) %>%
    mutate(id = row_number()) %>%
    spread(ind, rules) %>%
    select(-id) %>%
    rename(
      Code = 1,
      Description = 2
    ) %>% # next two lines remove "" characters if we need them
    mutate(Code = substr(Code, 2, nchar(Code)-1)) %>%
    mutate(Description = substr(Description, 2, nchar(Description)-1));
  ms_clean_ridership_rules
}

rules_list <- lapply(ms_filepaths, MS_RulesImport)
# turns out they're all identical, but whatever we'll keep them around for now




##### STEP 2 -> read in the ridership from routesum reports
rs_filepaths <- dir('data//raw//', full.names = T, pattern = "EVENT SUMMARY")
rs_names <- str_sub(str_match(rs_filepaths, pattern = "\\w{7,}\\s\\d"),start = 1,end = 3)


RS_RidershipImport <- function(rs_filepath){
  rs_ridership_first <- rs_filepath %>%
    readLines() %>%
    grep("Ridership By Route", .) %>%
    first()
  
  rs_ridership_last <- rs_filepath %>%
    readLines() %>%
    grep("TOTAL",.)-1
  
  rs_ridership_last <- rs_ridership_last[1]
  
  rs_dirty <- rs_filepath %>%
    read.table(skip=rs_ridership_first, header = TRUE, nrows = rs_ridership_last-rs_ridership_first, sep = ",")
  
  rs_clean <- rs_dirty %>%
    select(-starts_with("X"), -Token.Count, -Ticket.Count, -Preset.Preset1)
  ;
  rs_clean
}
ridership_list <- lapply(rs_filepaths, RS_RidershipImport)
names(ridership_list) <- rs_names


##### STEP 3 _> read in the transaction details
td_filepaths <- dir('data//raw//', full.names = T, pattern = "TRANSACTION DETAIL")
td_names <- str_match(td_filepaths, pattern = "\\w{7,}\\s\\d+,") %>% str_sub(start = 1, end = -2)

TD_TransactionImport <- function(td_filepath){
  td_first <- td_filepath %>%
    readLines() %>%
    grep("Type",.) %>%
    first()-1
  
  td_last <- td_filepath %>%
    readLines() %>%
    grep("Number of Tran",.)-2 %>%
    last()
  
  td_dirty <- td_filepath %>%
    read.table(skip=td_first, header = TRUE, nrows = td_last-td_first, sep =",")
  
  td_clean <- td_dirty %>%
    select(-Direction, -Fareset, -Stop, -Trip) %>%
    convert(chr(Type,
                Bus,
                Route,
                Run,
                Driver,
                Description))
  ; td_clean
}
td_list <- lapply(td_filepaths, TD_TransactionImport)
names(td_list) <- td_names
td_list_concat <- list("December" = rbindlist(list(td_list$`DECEMBER 1`,td_list$`DECEMBER 16`)),
                       "January" = td_list$`JANUARY 1`,
                       "November" = rbindlist(list(td_list$`NOVEMBER 1`, td_list$`NOVEMBER 16`)),
                       "October" = td_list$`OCTOBER 27`)
#clean up some memory
rm(td_list)
##### STEP 4 Generate the Fare Diff Table and see wazzup
GenerateFareDiff <- function(i){
  # i = 1
   x <- td_list_concat[[i]]
   y <- rules_list[[i]]
   z <- ridership_list[[i]]
    
  ridership_test <- x %>%
    filter(Description %in% y$Code | 
             Type %like% "118") %>%
    group_by(Route) %>%
    summarize(count = n()) %>%
    arrange(as.integer(Route)) %>%
    rename(Ridership_mine = count)
  
  fare_diff <- ridership_test %>%
    inner_join(z, by = "Route") %>%
    select(Route, Ridership, Ridership_mine) %>%
    mutate(Ridership_diff = Ridership_mine-Ridership) %>%
    mutate(percent_disagree = round((Ridership_diff/Ridership)*100,digits = 3));
  fare_diff
}  
# generate and rename
summarylist <- lapply(list(1,2,3,4), GenerateFareDiff)
names(summarylist) <- names(td_list_concat)

# looks good except for January, not sure what's going on with that one

# create used TD_DEC frame
Dec_TD_Used <- td_list_concat$December %>% filter(Description %in% rules_list[[1]]$Code |
                                                    Type %like% "118")

# format dates
Dec_TD_Used$Date.and.Time <- lubridate::mdy_hms(Dec_TD_Used$Date.and.Time)
Dec_TD_Used$Date <- as.Date(str_sub(Dec_TD_Used$Date.and.Time, 1, 10))
Dec_TD_Used$Clock_Time <- str_sub(Dec_TD_Used$Date.and.Time, 12, 19)
Dec_TD_Used$DateTest <- ifelse(Dec_TD_Used$Clock_Time < "03:00:00" , 1, 0)

#change transit day based on datetest
Dec_TD_Used$Transit_Day_Unix <- ifelse(Dec_TD_Used$DateTest == 1,
                                        lubridate::as_date(Dec_TD_Used$Date - 1),
                                        Dec_TD_Used$Date)
# add two dates together
Dec_TD_Used$Epoch_Date <- as.Date("1970-01-01")
Dec_TD_Used$Transit_Day <- Dec_TD_Used$Epoch_Date + lubridate::days(Dec_TD_Used$Transit_Day_Unix)

# get sec since midnight
Dec_TD_Used$seconds_between_dates <- difftime(Dec_TD_Used$Date,
                                               Dec_TD_Used$Transit_Day,
                                               units = "secs")

Dec_TD_Used$seconds_since_midnight_GPS_Time <- difftime(Dec_TD_Used$Date.and.Time,
                                                        Dec_TD_Used$Date,
                                                        units = "secs")

# add those two seconds to get seconds since (true) midnight

Dec_TD_Used$seconds_since_midnight <- Dec_TD_Used$seconds_since_midnight_GPS_Time +
  Dec_TD_Used$seconds_between_dates

# clean the format up (dplyr no like POSIXlt)

Dec_TD_Used$seconds_since_midnight_in_seconds <- as.numeric(as.character(Dec_TD_Used$seconds_since_midnight))



# import VMH sample data and find out how we can join it to the used Dec Data
VMH_samplepath <- dir('data//raw//', full.names = T, pattern = "VMH")
VMH_raw <- data.table::fread(file = VMH_samplepath, header = TRUE, data.table = FALSE)


#split RB and MB
# VMH_RB <- VMH_raw %>% filter(Latitude > 39.709465, Latitude < 39.877512)
# VMH_MB <- VMH_raw %>% filter(Latitude < 39.709465 | Latitude > 39.877512) %>%
#   mutate(MB_Area = case_when(Latitude > 39.877512 ~ paste(Trip, "North"),
#                              Latitude < 39.709465 ~ paste(Trip, "South")))

# forget the filters they didn't work, lets move on
#split
# VMH_MB_North <- VMH_MB %>% filter(Latitude > 39.877512)
# north_filter <- VMH_MB_North %>%
#   mutate(Vehicle_ID = as.character(Vehicle_ID), #we have to convert these so that they'll be able to join later
#          Trip = as.character(Trip)) %>%
#   group_by(Vehicle_ID, Trip, Transit_Day) %>%
#   summarize(start = min(Time.x), end = max(Time.x))
# 
# # intervals didn't work 
# #add the interval as a new col
# north_filter$interval <- interval(north_filter$start, north_filter$end)
# north_filter$interval_length <- int_length(north_filter$interval)
# 
# north_filter




# do a rolling join, joining TD to last VMH Time
# first we'll add a join_time column
# let's clean up the TD Data a bit shall we
Route_90_TD_Used <- Dec_TD_Used %>%
  filter(Route == "90") %>%
  select(-Latitude, -Longitude,
         -seconds_since_midnight,
         -seconds_since_midnight_GPS_Time,
         -seconds_since_midnight_in_seconds,
         -seconds_between_dates,
         -Transit_Day_Unix,
         -DateTest)

# add a join time column and clean up the rest
Route_90_TD_Used$join_time <- as.POSIXct(Route_90_TD_Used$Date.and.Time, tz = "UTC")
                                                                        # [,c("Latitude",
                                                                        #   "Longitude",
                                                                        #   "seconds_since_midnight",
                                                                        #   "seconds_since_midnight_GPS_Time",
                                                                        #   "seconds_since_midnight_in_seconds",
                                                                        #   "seconds_between_dates",
                                                                        #   "Transit_Day_Unix",
                                                                        #   "DateTest"):=NULL]

# fix data types
Route_90_TD_Used$Transit_Day <- as.character(Route_90_TD_Used$Transit_Day)
Route_90_TD_Used <- Route_90_TD_Used %>%
  select(Type,
         Date.and.Time,
         Bus,
         Route,
         Run,
         Description,
         Transit_Day,
         join_time)

# and set the key
setDT(Route_90_TD_Used)
setkey(Route_90_TD_Used, Bus, Transit_Day, join_time)

#let's add and clean the vmh data now

Route_90_VMH <- VMH_raw %>%
  select(Vehicle_ID,
         Time.x,
         Trip,
         Boards,
         Alights,
         Latitude,
         Longitude,
         GPSStatus,
         Transit_Day)

Route_90_VMH <- copy(data.table(Route_90_VMH))

Route_90_VMH[, join_time := as.POSIXct(Time.x, tz="UTC")]

#fix data types
Route_90_VMH[,Vehicle_ID:=as.character(Vehicle_ID)]

setkey(Route_90_VMH, Vehicle_ID, Transit_Day, join_time)


# now let's do our roll join!
# we will search within VMH, using TD times as the search, matching exactly
rolljoinexact <- Route_90_VMH[Route_90_TD_Used, roll = TRUE, allow = F, mult = "last"] %>% #the nomatch will omit rows for which there is no match between VMH and TD Used
  select(VMH_Time = Time.x,
         TD_Time = Date.and.Time,
         join_time,
         Vehicle_ID,
         everything())
  
  
# rearrange some columns
rolljoinexact <- rolljoinexact[,timediffs := as.difftime(as.ITime(TD_Time) - as.ITime(VMH_Time),units = "secs")]%>% 
  select(VMH_Time,
         TD_Time,
         timediffs,
         join_time,
         everything())

#don't need this
# # make a table of all big timediffs for future reference
# rolljointibblebigdiff <- as_tibble(rolljoinexact) %>% 
#   filter(timediffs>200) %>%
#   select(VMH_Time,
#          TD_Time,
#          timediffs,
#          join_time,
#          everything())


#make maxtime table to compare to, any GFI data outside the max will be considered having "missing VMH data"
maxtimes <- VMH_raw %>%
  mutate(Vehicle_ID = as.character(Vehicle_ID)) %>%
  group_by(Vehicle_ID,
           Transit_Day) %>%
  summarize(maxtime = as.character(max(as.POSIXct(Time.x,tz="UTC"))))
# don't need this either 
# #join the two and then filter
# rolljointibblebigdiff <- rolljointibblebigdiff %>% left_join(maxtimes) %>%
#   select(maxtime,
#          everything()) #%>% add this in if you want the data with "missing VMH data"
#   # filter(TD_Time < maxtime)


#add maxtimes so we can do some comparo
rolljoinexact <- rolljoinexact %>% left_join(maxtimes) %>%
  select(maxtime,everything())


# now lets summarize it, and get the 'Local Ridership' by filtering the lat/long
# first we'll set the boundaries
north_boundary <- 39.877512
south_boundary <- 39.709468

Local_Ridership_Exact_Match <- as_tibble(rolljoinexact) %>%
  filter(Latitude>north_boundary | Latitude<south_boundary) %>%
  summarize(Local90ExactMatch=n())


# let's join with a threshold, we'll do 1.5 minutes
rolljoinfuzzy <- Route_90_VMH[Route_90_TD_Used, roll = -60*2, nomatch= 0] %>% #the nomatch will omit rows for which there is no match between VMH and TD Used
  select(VMH_Time = Time.x,
         TD_Time = Date.and.Time,
         join_time,
         Vehicle_ID,
         everything())
# now we'll filter for local service
Local_Ridership_Fuzzy_Match <- as_tibble(rolljoinfuzzy) %>%
  filter(Latitude > north_boundary | Latitude < south_boundary) %>%
  summarize(Local90FuzzyMatch=n())

Local_Comparison <- cbind(summarylist$December,Local_Ridership_Exact_Match, Local_Ridership_Fuzzy_Match) %>%
  filter(Route=="90")

#let's get our % of VMH with bad GPS
Route_90_VMH_Bad_GPS_pct <- Route_90_VMH %>%
  filter(GPSStatus != 2 | is.na(GPSStatus)) %>%
  nrow()/nrow(Route_90_VMH)*100

# the following is the % of  TD_Data with bad or missing GPS, this will include the vehicles that do not report GPS data at all
Route_90_TD_Bad_GPS_pct <- rolljoinexact %>%
  filter(GPSStatus != 2 | is.na(GPSStatus)) %>%
  nrow()/nrow(rolljoinexact)*100

# transactions after VMH
Route_90_TD_After_VMH <- rolljoinexact %>%
  filter(as.POSIXct(TD_Time,tz="UTC") > as.POSIXct(maxtime,tz="UTC"))

# transactions that are in gaps in the data
Route_90_TD_gap_data <- rolljoinexact %>%
  filter(as.POSIXct(TD_Time, tz = "UTC") < as.POSIXct(maxtime,tz="UTC")
         & timediffs > 60*2)

# sum those and get the percentage of questionable data
Questionable_TD_pct <- rbind(Route_90_TD_After_VMH, Route_90_TD_gap_data,
                         rolljoinexact %>%
                           filter(GPSStatus != 2 |is.na(GPSStatus))) %>%
  nrow()/nrow(rolljoinexact)*100

percent_summary <- cbind(Bad_VMH_pct = paste(round(Route_90_VMH_Bad_GPS_pct,3),"%"),
                         count_VMH = nrow(Route_90_VMH),
                         Bad_TD_pct = paste(round(Route_90_TD_Bad_GPS_pct,3),"%"),
                         Questionable_TD_pct = paste(round(Questionable_TD_pct,3),"%"),
                         count_TD = nrow(rolljoinexact))
view(percent_summary)



rolljoincounts <- rolljoinexact %>% group_by(as.Date(Transit_Day),
                                             Vehicle_ID) %>%
  summarize(roll_count = n())

DecTDcounts <- Dec_TD_Used %>% 
  filter(Route == "90") %>%
  group_by(Transit_Day,
           Bus) %>%
  summarize(TD_count = n())


# VALIDATE BY COUNT BY BUS BY DATE
joinedcounts <- rolljoincounts %>%
  left_join(DecTDcounts, by = c("Vehicle_ID" = "Bus", "as.Date(Transit_Day)"="Transit_Day")) %>%
  mutate(diff = TD_count - roll_count) %>%
  filter(diff != 0)

view(joinedcounts)

testjoin <- filter(rolljoinexact, Vehicle_ID == "1976", Transit_Day == "2019-12-03") %>%
  left_join(filter(Route_90_TD_Used, Bus == "1976", Transit_Day == "2019-12-03"),by=c("TD_Time"="Date.and.Time"))

testjoin <- cbind(filter(rolljoinexact, Vehicle_ID == "1976", Transit_Day == "2019-12-03"), rbind(filter(Route_90_TD_Used, Bus == "1976", Transit_Day=="2019-12-03")))
  

wut <- VMH_raw %>% mutate(missing_GPS = case_when(GPSStatus == 0 ~ 0,
                                           TRUE ~ 1)) %>%
  group_by(Transit_Day, Trip) %>%
  summarize(missingcount = sum(missing_GPS))
